extern crate cbindgen;

use std::env;
use cbindgen::Config;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_language(cbindgen::Language::C)
        .with_crate(crate_dir)
        .with_documentation(true)
        .with_include_guard("LIBRSA")
        .with_header("// This file is autogenerated by:\n//   cbindgen --config cbindgen.toml lib.rs >c_bindings/librsa.h\n// Don't modify manually.")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("c_bindings/librsa.h");
}