// This file is autogenerated by:
//   cbindgen --config cbindgen.toml lib.rs >c_bindings/librsa.h
// Don't modify manually.

#ifndef LIBRSA
#define LIBRSA

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Buffer {
  uint8_t *data;
} Buffer;

void generate_pub_keys(void);

/**
 *Returns PEM format string with the public key. Length of string = 1679
 */
char *generate_priv_keys(uint32_t bits);

/**
 *Returns PEM format string with the public key. Length of string = 426
 */
char *generate_public_key(const char *rsa_private_key);

/**
 *Returns a 256 byte long byte array containing the encrypted string
 */
struct Buffer encrypt_string(char *pem_public_key, char *data);

/**
 *Returns a c_string with the unencrypted data
 */
char *decrypt_string(char *pem_private_key, uint8_t *data);

void free_buf(struct Buffer buf);

#endif /* LIBRSA */
